FROM node:1
# pull official base image

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

# install app dependencies
RUN npm install

WORKDIR ../frontend

# add app
COPY . ./

# start app
CMD ["npm", "start"]
