version: '3'

services:

  db:
    container_name: db
    image: mysql/mysql-server:5.7
    ports: 
      - 3306:3306
    volumes:
      - /var/lib/docker/volumes/mysql-volume/_data:/var/lib/mysql
        
  
  spring:
    container_name: spring
    image: spring-backend:dev
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080

  node:
    container_name: node
    image: node-frontend:dev
    restart: unless-stopped
    depends_on:
      - spring
    ports:
      - 80:3000
    volumes:
      - '../frontend/:/app'
      - '/app/node_modules'
