version: '3'

services:

  homeautomation-mysql:
    image: mysql/mysql-server:5.7
    ports: 
      - 3306:3306
    volumes:
      - /var/lib/docker/volumes/848a05dddcbc227287a680b7cdcc2bfe4af4d8d66c953b847dbc4ca5bc35e92c/_data:/var/lib/mysql
        
  
  homeautomation-spring:
    image: spring-backend:v1
    restart: on-failure
    depends_on:
      - homeautomation-mysql
    ports:
      - 8080:8080

  homeautomation-nodejs:
    container_name: homeautomation-node
    image: frontend:dev
    restart: unless-stopped
    depends_on:
      - homeautomation-spring
    ports:
      - 3001:3000
    volumes:
      - '../frontend/:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
