version: '3'

services:

  homeautomation-mysql:
    image: mysql/mysql-server:5.7
    ports: 
      - 3306:3306
  
  homeautomation-spring:
    image: spring-backend:v1
    restart: on-failure
    depends_on:
      - homeautomation-mysql
    ports:
      - 8080:8080
