# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ cicd_test ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [11]
    name: Java ${{ matrix.java }} sample
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      
      - name: npm install
        working-directory: ./frontend
        run: npm install \
          npm install dateformat \
          npm install react-scripts@3.4.1 -g
            
      - name: Docker Build Node
        working-directory: ./frontend
        run: docker build -t frontend:dev .

      - name:  Docker Build Spring
        working-directory: ./backend
        run: docker build -t spring-backend:dev .
        
      - name: Build the docker-compose stack
        working-directory: ./Docker
        run: docker-compose up -d
